<a href="https://colab.research.google.com/github/subhashini890/html/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df=pd.read_csv("/content/student_depression_dataset.csv")
df

id  Gender   Age           City Profession  Academic Pressure  \
0           2    Male  33.0  Visakhapatnam    Student                5.0   
1           8  Female  24.0      Bangalore    Student                2.0   
2          26    Male  31.0       Srinagar    Student                3.0   
3          30  Female  28.0       Varanasi    Student                3.0   
4          32  Female  25.0         Jaipur    Student                4.0   
...       ...     ...   ...            ...        ...                ...   
27896  140685  Female  27.0          Surat    Student                5.0   
27897  140686    Male  27.0       Ludhiana    Student                2.0   
27898  140689    Male  31.0      Faridabad    Student                3.0   
27899  140690  Female  18.0       Ludhiana    Student                5.0   
27900  140699    Male  27.0          Patna    Student                4.0   

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0   
1                0.0  5.90                 5.0               0.0   
2                0.0  7.03                 5.0               0.0   
3                0.0  5.59                 2.0               0.0   
4                0.0  8.13                 3.0               0.0   
...              ...   ...                 ...               ...   
27896            0.0  5.75                 5.0               0.0   
27897            0.0  9.40                 3.0               0.0   
27898            0.0  6.61                 4.0               0.0   
27899            0.0  6.88                 2.0               0.0   
27900            0.0  9.24                 1.0               0.0   

            Sleep Duration Dietary Habits      Degree  \
0              '5-6 hours'        Healthy     B.Pharm   
1              '5-6 hours'       Moderate         BSc   
2      'Less than 5 hours'        Healthy          BA   
3              '7-8 hours'       Moderate         BCA   
4              '5-6 hours'       Moderate      M.Tech   
...                    ...            ...         ...   
27896          '5-6 hours'      Unhealthy  'Class 12'   
27897  'Less than 5 hours'        Healthy         MSc   
27898          '5-6 hours'      Unhealthy          MD   
27899  'Less than 5 hours'        Healthy  'Class 12'   
27900  'Less than 5 hours'        Healthy         BCA   

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0   
1                                        No               3.0   
2                                        No               9.0   
3                                       Yes               4.0   
4                                       Yes               1.0   
...                                     ...               ...   
27896                                   Yes               7.0   
27897                                    No               0.0   
27898                                    No              12.0   
27899                                   Yes              10.0   
27900                                   Yes               2.0   

      Financial Stress Family History of Mental Illness  Depression  
0                  1.0                               No           1  
1                  2.0                              Yes           0  
2                  1.0                              Yes           0  
3                  5.0                              Yes           1  
4                  1.0                               No           0  
...                ...                              ...         ...  
27896              1.0                              Yes           0  
27897              3.0                              Yes           0  
27898              2.0                               No           0  
27899              5.0                               No           1  
27900              3.0                       

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import KBinsDiscretizer

def prepare_data():
    iris = load_iris()
    x = iris.data
    y=iris.target


    discretizer = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="uniform")
    X_binned = discretizer.fit_transform(x)
    df = pd.DataFrame(X_binned, columns=iris.feature_names)
    categories = ['LOW', 'MEDIUM', 'HIGH']
    return df
df=prepare_data()
df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  0.0               1.0                0.0               0.0
1                  0.0               1.0                0.0               0.0
2                  0.0               1.0                0.0               0.0
3                  0.0               1.0                0.0               0.0
4                  0.0               1.0                0.0               0.0
..                 ...               ...                ...               ...
145                2.0               1.0                2.0               2.0
146                1.0               0.0                2.0               2.0
147                1.0               1.0                2.0               2.0
148                1.0               1.0                2.0               2.0
149                1.0               1.0                2.0               2.0

[150 rows x 4 columns]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import KBinsDiscretizer

def prepare_data():
    iris = load_iris()
    x = iris.data
    y = iris.target


    discretizer = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="uniform")
    X_binned = discretizer.fit_transform(x)
    cat=["LOW","MEDIUM","HIGH"]
    df = pd.DataFrame(X_binned, columns=iris.feature_names)
for col in df_columns:
  df[col]=df[col].apply(lambda x:cat[int(x)])
df['Traget']==['Yes' if label==0 else 'NO' for label in y]
return df



NameError: name 'df_col' is not defined

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import KBinsDiscretizer,LabelEncoder

def prepare_data():
  iris = load_iris()
  x = iris.data
  y = iris.target


  discretizer = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="uniform")
  X_binned = discretizer.fit_transform(x)
  cat=["LOW","MEDIUM","HIGH"]
  df = pd.DataFrame(X_binned, columns=iris.feature_names)
  for col in df.columns:
    df[col]=df[col].apply(lambda x:cat[int(x)])

  df['Target']==['Yes' if label == 0 else 'NO' for label in y]

  return df


def encode_data(df):
  x=df.iloc[:,:-1]
  y=df.iloc[:,-1]

  k_list=[]
  for col in x.columns:
    k=LabelEncoder()
    x[col]=k.fit_transform(x[col])
    k_list.append(k)

  label_encoder=LabelEncoder()
  y=label_encoder.fit_transform(y)     #yes=1 and no=0
  return X.values,y


In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import KBinsDiscretizer, LabelEncoder

def prepare_data():
    iris = load_iris()
    x = iris.data
    y = iris.target

    # Discretize features into 3 bins
    discretizer = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="uniform")
    X_binned = discretizer.fit_transform(x)
    cat = ["LOW", "MEDIUM", "HIGH"]

    df = pd.DataFrame(X_binned, columns=iris.feature_names)

    # Map numerical bins to labels
    for col in df.columns:
        df[col] = df[col].apply(lambda val: cat[int(val)])

    # Fix assignment and spelling of 'Target'
    df['Target'] = ['Yes' if label == 0 else 'No' for label in y]

    return df

def encode_data(df):
    x = df.iloc[:, :-1]
    y = df.iloc[:, -1]

    k_list = []
    for col in x.columns:
        le = LabelEncoder()
        x[col] = le.fit_transform(x[col])
        k_list.append(le)

    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(y)  # Yes = 1, No = 0

    df = prepare_data()

    return x.values, y


In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import KBinsDiscretizer, LabelEncoder

def prepare_data():
    iris = load_iris()
    x = iris.data
    y = iris.target

    # Discretize features into 3 bins
    discretizer = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="uniform")
    X_binned = discretizer.fit_transform(x)
    cat = ["LOW", "MEDIUM", "HIGH"]

    df = pd.DataFrame(X_binned, columns=iris.feature_names)

    # Map numerical bins to labels
    for col in df.columns:
        df[col] = df[col].apply(lambda val: cat[int(val)])

    # Fix assignment and spelling of 'Target'
    df['Target'] = ['Yes' if label == 0 else 'No' for label in y]

    return df

def encode_data(df):
    x = df.iloc[:, :-1]
    y = df.iloc[:, -1]

    k_list = []
    for col in x.columns:
        le = LabelEncoder()
        x[col] = le.fit_transform(x[col])
        k_list.append(le)

    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(y)  # Yes = 1, No = 0

    return x.values, y

# Run the code
df = prepare_data()
X_encoded, y_encoded = encode_data(df)

print("Encoded Features (X):")
print(X_encoded[:5])
print("Encoded Target (y):")
print(y_encoded[:5])


Encoded Features (X):
[[1 2 1 1]
 [1 2 1 1]
 [1 2 1 1]
 [1 2 1 1]
 [1 2 1 1]]
Encoded Target (y):
[1 1 1 1 1]
